version: '3.0'
services:
  db:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  app:
    image: nbrink91/node-web-app
    ports:
      - 3000:3000
    links:
      - db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres